<?php $dir = ".."; include($dir . "/header.php"); ?>
<div id="content">
  <p class="filler">We are the robotics club, or team, of Tompkins High School.  We are known as the Steel Talons and we are a registered team with the non-profit organization, FIRST. Our FIRST Robotics Competition (FRC) team number is 5427.   Our team was established in the spring of 2014.  We competed in two off-season robotics competitions in the summer and fall of 2014 using other established teams borrowed backup robots.<br><br>
    In January of 2015, we built our first robot as a team at one of the mentor's home and then moved into the newly built RSC in March and then competed in our inaugural competition at Lone Star Regional Competition finishing in the low 30s.  In January 2016, we built our second robot as a team at the Robert Shaw Center (RSC) located near Raines High School and Rhodes Stadium. We competed in our second regional competition in April again at the Lone Star Regional competition finishing in the top 20.  We typically compete in a summer off season competition and an off season competition in the fall.<br><br>
    Interested students in 9th through 12th grade can join the team until December 1st.  A new FIRST Robotics Competition season begins in early January of each year where we build a new robot based on that particular year's requirements.  We have approximately 8 weeks to design and build a new robot.  And then we go to regional competitions and compete with the new robot. Our season is busiest in January and February and then in the weeks leading up to a regional competition in March/April.  In the fall semester our team gets trained in safety and how to use the equipment.  There are monthly meetings for all student members usually held before and after school, but all build activities take place up at the Robert Shaw Center (RSC).  Students must provide their own transportation to and from the RSC.<br><br>
    In order to participate on the team you need to complete the online membership form (see Communications tab) and pay the activity fee that covers a team t-shirt, competition pizza meal, and a small part of the competition fees or the build season costs. We limit team size due to space constraints at the RSC and manageability.<br><br>
    For authoring and development features of the site visit <a href = "/authoring">this page</a></p>
</div>
<?php include($dir . "/footer.php") ?>
